### ISSUE TITLE
只有callable，没有runnable吗

### ISSUE THREAD

**Issue by Georgeqhh** [houbb/sisyphus#15]
有些不需要返回值，还得返回个null,有点麻烦

**Comment by houbb** [comment]
没有 为了接口统一，就只设计了1个。

**Comment by Georgeqhh** [comment]
可以用多态，然后支持callable和runnable,主要是不需要返回值的时候还要返回null写着有点多余




√Mù`頭し..
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "houbb/sisyphus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月16日(星期四) 中午11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [houbb/sisyphus] 只有callable，没有runnable吗 (Issue #15)





 
Closed #15 as completed.
