### ISSUE TITLE
重试方法切点定义范围太大

### ISSUE THREAD

**Issue by cao2358** [houbb/sisyphus#2]
提一个问题，的切点定义的是所有的public方法
@Pointcut("execution(public * *(..))")
需要修改成只监听对应注解的方法，不然项目启动不允许这么大范围的AOP，我们目前是自己覆写了

**Comment by houbb** [comment]
感谢提醒，最近比较忙。后面有时间我改一下，

**Comment by houbb** [comment]
v0.0.8 版本已调整为按照注解 `@Retry` 进行扫描。

后续遇到其他问题及时沟通，也欢迎提 PR。
