### ISSUE TITLE
监听器第一次不打印日志？

### ISSUE THREAD

**Issue by yanxiaochuan** [houbb/sisyphus#5]
![6E150837-324B-4305-8BDA-E69369727C73](https://user-images.githubusercontent.com/7532142/98066035-d0ac2a80-1e90-11eb-97d2-301c37cf2473.png)

**Comment by houbb** [comment]
忽然发现这个没回复，抱歉。

包括第一次程序本身执行。第一次时程序的正常执行，所以没有相关日志。
